### ISSUE TITLE
add k3s token support

### ISSUE THREAD

**Issue by miekg** [virtual-kubelet/systemk#7]
this is taken from the k3s site, and even though it's k3s specific it will simplify my intended use case for it, namely using it with k3s first.
~~~
sudo k3s server &
# Kubeconfig is written to /etc/rancher/k3s/k3s.yaml
sudo k3s kubectl get node

# On a different node run the below. NODE_TOKEN comes from /var/lib/rancher/k3s/server/node-token
# on your server
sudo k3s agent --server https://myserver:6443 --token ${NODE_TOKEN}
~~~
This still doesn't solve the TLS cert issue, but makes bootstrapping slightly easier.

**Comment by miekg** [comment]
hmmm, this requires surgery on the vk side as (obvs) this is not supported there.

I'll leave this open for some time, but I don't think it can be done easily.

**Comment by pires** [comment]
TLS bootstrapping is not supported by VK and maybe that's something we should work on.

To be clear, the VK expects a working kubeconfig, which is the result of the TLS bootstrap process. The token you mention above is _most likely_ used as an OTP kind of thing to authenticate against Kubernetes and get the TLS sorted out. I say _most likely_ because I don't know enough of k3s but this is the process that `kubeadm` follows.

**Comment by miekg** [comment]
yes, it's a hash of the certs you need to pull out from the k3s's apiserver which then allows some verification on the client side.

Once you have all this and you can connect to the API server, I was thinking of dumping the new certs in a well-known config map that can be read by VK and it will then re-initialize. This would at least constrain the problem to the bootstrap stage.

**Comment by miekg** [comment]
will not implement token support, too k3s specific.
